### ISSUE TITLE
Parsing ELWC example to tensors consumable by a non-EIE model

### ISSUE THREAD

**Issue by edwardchor** [tensorflow/ranking#244] opened 2021-01-23 22:06 UTC
- versions:
  - tensorflow==2.3.2
  - tensorflow-ranking==0.3.0
- description:
  When the example list only contains one item, the model graph can consume the tensors parsed by tfr's parser, however, when the number of items >=2, we got errors like this from tf-serving: the following example has an item list (example list) of 2.
```
ERROR:
  Code: InvalidArgument
  Message: Input to reshape is a tensor with 4 values, but the requested shape has
 2
         [[{{node dnn/input_from_feature_columns/input_layer/feature_A_indicator_1/Reshape}}]]
```
Here `feature_A` is an indicator column of bucket size ==2, default to 0. The model is DNNLinearCombinedEstimator.

By looking at the source code, I've noticed that ELWC parser is actually EIE parser, so I'm wondering if it's because the parser constructs the tensors to a EIE fashion, so that our model can not consume the model is expecting plain batched examples?

I've tried changing the parser source code to alter the output tensors, but no luck.
Any idea?
Thank you!

**Comment by xuanhuiwang** [comment] 2021-01-25 18:20
I guess you may have used the Regress API in TF-Serving, which only accepts tf.Example as the model input (though the TF-Serving API accepts ELWC). To fix your problem, I think you need to export a model from TF-Ranking to accept tf.Example as your input format. In some of our examples, set listwise_inference=False.

ELWC and EIE parsers look very similar. But they are two different ones. The error should not come from there, I think.

**Comment by edwardchor** [comment] 2021-01-25 19:55
> I guess you may have used the Regress API in TF-Serving, which only accepts tf.Example as the model input (though the TF-Serving API accepts ELWC). To fix your problem, I think you need to export a model from TF-Ranking to accept tf.Example as your input format. In some of our examples, set listwise_inference=False.
> 
> ELWC and EIE parsers look very similar. But they are two different ones. The error should not come from there, I think.

Thanks for the reply!
Could you share more details on  `export a model from TF-Ranking`? Currently our model training and exporting is handled by `tf.estimator.train_and_evaluate`, are you referring a different way?

Thank you!

**Comment by xuanhuiwang** [comment] 2021-01-26 00:15
Can you take a look at the example code here: https://github.com/tensorflow/ranking/blob/master/tensorflow_ranking/examples/tf_ranking_tfrecord.py#L168? We take care of different serving input fn when exporting.

Note that tf.Example as the serving input format is only supported for group_size = 1.

**Comment by martinbomio** [comment] 2021-01-26 14:48
Hi @xuanhuiwang I am working with @edwardchor on this and just wanted to add some more information on the issue.

We use the gRPC `Predict` API for tensorflow serving. 
We are also exporting the model with a signature created with this function of tensorflow ranking https://github.com/tensorflow/ranking/blob/master/tensorflow_ranking/g3doc/api_docs/python/tfr/data/build_ranking_serving_input_receiver_fn.md.

So basically, we are serializing and `ExampleListWithContext` as a `TensorProto` when calling tensorflow serving through the `Predict` API. We will like to use `ExampleListWithContext` and not `Example` because we want to make use of the shared features or `context` to avoid sending them on each example, and in the future to also use pair wise or list wise ranking algos.

We got all this to work, except for the part that the `example` and `context` tensors being parsed by the signature do not have the shape we expect, they seem to be flatten into the first dimension instead of creating the "matrix" we expect.

To add a bit more info, we used to use this function to build a serving signature in tf 1.15 and it worked as we expected.

**Comment by jpvelez** [comment] 2021-01-26 17:16
We're running into this issue at Spotify as well. Everything was working fine with TF 1.x and now we're getting the same error. In our case, we can't served with regular `tf.Example`, because we're building in-house contextual bandit models that requires all records being sent in a single batch, which is why we're using ELWC.

**Comment by xuanhuiwang** [comment] 2021-01-26 20:05
@martinbomio @jpvelez: Thanks for the additional information. We will do some debugging internally.

One more question: for TF-Serving, do you use the Python API or others?

**Comment by martinbomio** [comment] 2021-01-26 20:18
thanks @xuanhuiwang. We use the tensorflow serving through gRPC

**Comment by xuanhuiwang** [comment] 2021-01-27 00:19
@martinbomio, what about the client code which send and receive the gRPC? Is that in Python or C++?

**Comment by martinbomio** [comment] 2021-01-27 00:21
hi @xuanhuiwang, in production, it is java, through gRPC stubs. But we also tried it through python and `grpcurl` and saw the same issue

**Comment by xuanhuiwang** [comment] 2021-01-27 00:41
Got it. Did you try to validate the model using something like the following? The model is stored at `saved_model_dir` and `serialized_elwcs` contains a batch of serialized elwcs strings?

```
    sess = tf.compat.v1.Session(graph=tf.Graph())
    meta_graph_def = tf.compat.v1.saved_model.loader.load(
        sess, [tf.saved_model.SERVING], saved_model_dir)
    signature = self._meta_graph_def.signature_def["predict"]

    inputs = {signature.inputs['example_list'].name: serialized_elwcs}
    scores = sess.run(signature.outputs["output"].name, inputs)
```

How about a v2 version without tf.compat.v1.Session, like something here: https://www.tensorflow.org/api_docs/python/tf/saved_model/load?

**Comment by martinbomio** [comment] 2021-01-27 00:44
yes, we have actually tried both ways, and the same exact error is thrown when running through the example code you just shared and tensorflow serving.

The exact code used was:
```
with tf.compat.v1.Graph().as_default():
    with tf.compat.v1.Session() as sess:
        elwc_model = tf.saved_model.load(local_dir)
        init = tf.compat.v1.global_variables_initializer()
        sess.run(init)
        
        prediction = elwc_model.signatures["regression"](inputs=tf.constant([proto_message.SerializeToString()]))['outputs']

        prediction.eval(session=sess)

```

here `regression` signature is the signature built with [build_ranking_serving_input_receiver_fn](https://github.com/tensorflow/ranking/blob/master/tensorflow_ranking/g3doc/api_docs/python/tfr/data/build_ranking_serving_input_receiver_fn.md) just poorly named to `regression` :)

**Comment by martinbomio** [comment] 2021-01-27 20:52
@xuanhuiwang we might have a lead into why the `build_ranking_serving_input_receiver_fn` might not be working for us.

Looking at the docs [here](https://github.com/tensorflow/ranking/blob/1ee0788997510c6e0a76c57bca7d7864b71be130/tensorflow_ranking/python/data.py#L319-L329) it seems like the context feature tensors won't have the same shape and dimensions as the example features.

We are trying if repeating and reshaping the context feature tensors to match the shape of the example feature tensors can solve our issue.

In practice, this would mean that the parsing function would behave the same way as if a batch of `tf.example` features were passed (which is what we want).

Does that make sense?

**Comment by xuanhuiwang** [comment] 2021-01-27 21:16
@martinbomio, The `build_ranking_serving_input_receiver_fn` expects that context_features have different shape from example_features.  I guess this is not the root cause. Also, the same code works for TF1.x but not TF2.2.

In the python code above, what is the error message? Can you share the code stack of the error?

From the original post, it does sounds that there are some re-shape issues. If we are able to re-produce the error, that will be much more helpful.

**Comment by martinbomio** [comment] 2021-01-27 21:30
> The build_ranking_serving_input_receiver_fn expects that context_features have different shape from example_features. I guess this is not the root cause.

@xuanhuiwang I think this might actually be our problem, since our model initially used a serving function that accepted tf.example, and we migrate it to us `ExampleListWithContext` instead, with the hopes that the actual feature tensors dimensions will be the same as sending a batch of `tf.examples`.

**Comment by xuanhuiwang** [comment] 2021-01-27 23:51
We are able to reproduce a similar error. Will look into it.

**Comment by xuanhuiwang** [comment] 2021-01-28 00:23
Not sure which code path you are using to train the model. It looks that the problem may come from your transform_fn or transform_function. The current error suggests that you export a model that accepts tf.Example, but you intent is to accept ELWC.

The following code is what we provided in our EstimatorBuilder:
https://github.com/tensorflow/ranking/blob/master/tensorflow_ranking/python/estimator.py#L280-L294

If self._hparams.get("listwise_inference") is False, it exports a model that accept tf.Example. Make sure your pipeline not trigger `encode_pointwise_features`. Or simply use the following as the transform_fn

```
  feature.encode_listwise_features(
          features=features,
          context_feature_columns=self._context_feature_columns,
          example_feature_columns=self._example_feature_columns,
          mode=mode,
          scope="transform_layer")
```

**Comment by ramakumar1729** [comment] 2021-01-28 00:34
Can you provide more details on how the Estimator is built? Are you using (1) tf.estimator.DNNLinearCombinedEstimator, or (2) building a ranking estimator using tensorflow_ranking APIs? The first option might not support 3D example features and 2D context features. 

In the second option, make sure you are not using `encode_pointwise_features` in transform_fn, and are using `tfr.data.build_ranking_serving_input_receiver_fn`for listwise inference.

**Comment by martinbomio** [comment] 2021-01-28 15:06
@ramakumar1729 we are using `tf.estimator.DNNLinearCombinedEstimator`.
> The first option might not support 3D example features and 2D context features.
This makes sense, I think that's what we are seeing.

Do you have any recommendations on what we could do to enable `ExampleListWithContext` aware signatures for such models (or any models in general). Based on our tests, we've seen a huge performance imporvement when serving the model through this format since it is a more efficient way to send a batch of items to be scored (because of the shared `context` features)

**Comment by ramakumar1729** [comment] 2021-01-28 18:19
Since the estimator in this case expects features of 2D shape `[batch_size, feature_dims]`, you would need to align your serving input_fn to produce this. [tfr.data.build_ranking_serving_input_receiver_fn_with_parsing_fn](https://github.com/tensorflow/ranking/blob/1ee0788997510c6e0a76c57bca7d7864b71be130/tensorflow_ranking/python/data.py#L978) supports a custom `parsing_fn` where you can transform the features appropriately. You can reuse the`parsing_fn` with your training `input_fn` to avoid any train-serve discrepancy. 

Such a custom `parsing_fn` would parse ELWC to feature dict and do the following as well:

- Modifying 2D context to 3D features to align with example features. You can do something like:
  ```
   context_feature = tf.expand_dims(context_features[name], axis=1)
        context_feature = tf.tile(
            context_feature, multiples=[1, list_size, 1]) 
  ```
- Flatten all 3D context and example features to 2D via reshape. Essentially, features are of shape `[expanded_batch_size, feature_dims]`, where `expanded_batch_size = batch_size * list_size`.
- Reshape final output to match expected shape, e.g., `[batch_size * list_size, 1] -> [batch_size, list_size]`.

We are working on open sourcing some keras layers which provide such utilities.

Let us know if this addresses the issue you are facing.

**Comment by martinbomio** [comment] 2021-01-28 20:21
thanks @ramakumar1729 open-sourcing such utility functions would be great!

We were able to do what you suggest in the following way (it might need some cleanup, and still doesn't cover the output reshape to allow batching) 

```
def build_ELWC_from_feature_columns_serving_input_receiver_fn(
    context_feature_columns=None,
    example_feature_columns=None,
    default_batch_size=None,
    input_name="inputs",
):
    """
    Build a serving_input_receiver_fn expecting ExampleListWithContexts.
    Adapted from
    tensorflow.estimator.export.build_parsing_serving_input_receiver_fn.
    """

    def serving_input_receiver_fn():
        """An input_fn that expects a serialized ExampleListWithContext."""
        context_feature_spec = tf.feature_column.make_parse_example_spec(
            context_feature_columns
        ) if context_feature_columns else None
        example_feature_spec = tf.feature_column.make_parse_example_spec(
            example_feature_columns
        ) if example_feature_columns else None
        serialized = tf.compat.v1.placeholder(
            dtype=tf.dtypes.string,
            shape=[default_batch_size],
            name="input_ranking_tensor",
        )
        receiver_tensors = {input_name: serialized}
        features = tfr.data.parse_from_example_list(
            serialized,
            context_feature_spec=context_feature_spec,
            example_feature_spec=example_feature_spec,
            size_feature_name="list_size"
        )

        # the context features are parsed into tensors of shape [batch_size, feature_dim] by
        # tfr.data.parse_from_example_list so we need modify them to 3D features to align
        # with example features tensors to get a shape of [batch_size, list_size, feature_dim].
        # We do this by adding an extra dimenson and then repeating the dimension value list_size times.
        if context_feature_spec:
            for name in context_feature_spec.keys():
                list_size = tf.shape(features["list_size"])[0]
                context_feature = tf.expand_dims(features[name], axis=1)
                features[name] = tf.tile(context_feature, multiples=[1, list_size, 1])

        # Seems the models accept 2D tensors of we need to reshape all of the feature
        #  tensors to have dimensions (batch_size * list_size, feature_dim)
        for name in features.keys():
            if name != "list_size":
                shape = tf.shape(features[name])
                features[name] = tf.reshape(features[name], shape=(shape[0] * shape[1], shape[2]))

        return ServingInputReceiver(features, receiver_tensors)

    return serving_input_receiver_fn
```

Is there a way we can track the addition of the utility functions for us to be aware when they are available in tensorflow-ranking?

**Comment by ramakumar1729** [comment] 2021-01-28 22:17
This logic seems correct overall. Does this work with your Estimator and export a SavedModel successfully?

For the new layers, we will make a new release for it and have an announcement, so if you are subscribed to the repo, you should see it.

**Comment by martinbomio** [comment] 2021-01-28 22:39
@ramakumar1729 it seems to be working if no `SparseTensor` is used, we are having a bit of a hard time making it work with sparse tensors.

We changed the above function to something like this to handle sparse tensors:
```python

def build_ELWC_serving_input_receiver_fn(
    context_feature_spec=None,
    example_feature_spec=None,
    default_batch_size=None,
    input_name="inputs",
):
    """
    Build a serving_input_receiver_fn expecting ExampleListWithContexts.
    Adapted from
    tensorflow.estimator.export.build_parsing_serving_input_receiver_fn.
    """

    def serving_input_receiver_fn():
        """An input_fn that expects a serialized ExampleListWithContext."""
        serialized = tf.compat.v1.placeholder(
            dtype=tf.dtypes.string,
            shape=[default_batch_size],
            name="input_ranking_tensor",
        )
        receiver_tensors = {input_name: serialized}
        features = tfr.data.parse_from_example_list(
            serialized,
            context_feature_spec=context_feature_spec,
            example_feature_spec=example_feature_spec,
            size_feature_name="list_size"
        )

        list_size = tf.shape(features["list_size"])[0]
        # the context features are parsed into tensors of shape [batch_size, feature_dim] by
        # tfr.data.parse_from_example_list so we need modify them to 3D features to align
        # with example features tensors to get a shape of [batch_size, list_size, feature_dim].
        # We do this by adding an extra dimension and then repeating the dimension value list_size times.
        if context_feature_spec:
            for name in context_feature_spec.keys():
                shape = tf.shape(features[name])
                features[name] = tfr_utils.reshape_first_ndims(features[name], 1, [shape[0], list_size, shape[1]])

        # Seems the models accept 2D tensors of we need to reshape all of the feature
        #  tensors to have dimensions (batch_size * list_size, feature_dim)
        for name in features.keys():
            if name != "list_size":
                shape = tf.shape(features[name])
                new_shape = [shape[0] * shape[1], shape[2]]
                if isinstance(features[name], tf.SparseTensor):
                    features[name] = tf.sparse.reshape(features[name], new_shape)
                else:
                    features[name] = tf.reshape(features[name], shape=new_shape)

        return ServingInputReceiver(features, receiver_tensors)

    return serving_input_receiver_fn
```

but still getting some errors. It seems like some tensors are being reshaped to 4D tensors.

**Comment by ramakumar1729** [comment] 2021-01-28 22:51
@martinbomio You can use `x = tfr.utils.reshape_first_ndims(x, 2, [batch_size * list_size])` which works for both sparse and dense tensors.

**Comment by martinbomio** [comment] 2021-01-28 23:35
@ramakumar1729 can you explain why the `2` in the `first_ndims` param and where would you put that as part of the provided function?

**Comment by ramakumar1729** [comment] 2021-01-28 23:42
@martinbomio : since we are reshaping the first two dimensions `batch_size, list_size` to new shape: `[batch_size * list_size]`, we use `2` for first ndims.

**Comment by martinbomio** [comment] 2021-01-28 23:46
@ramakumar1729 thanks. I think the issue we are having is reshaping the context features (which are 2D tensors with [batch_size, feature_dim] to 3D tensors with [batch_size, list_size, feature_dim]).

I think your suggestion to use `x = tfr.utils.reshape_first_ndims(x, 2, [batch_size * list_size])` is for flattening the tensors before feeding them to the network. Is this correct?

**Comment by martinbomio** [comment] 2021-01-28 23:56
so basically doing what was suggested:
```
 context_feature = tf.expand_dims(context_features[name], axis=1)
      context_feature = tf.tile(
          context_feature, multiples=[1, list_size, 1]) 
```
doesn't quite work for sparse tensors

**Comment by ramakumar1729** [comment] 2021-01-29 00:05
@martinbomio : Good point, sparse tensors do not work with tile directly. You'll need to do something like this:
```
batch_size = 2
list_size = 5
feature_dims = 3
sp = tf.SparseTensor(indices=([[0, 0], [1, 0], [1, 1], [1, 2]]),
      values=["tensorflow", "learning", "to", "rank"],
      dense_shape=([batch_size, feature_dims]))

# Do tiling via sparse expand_dim and sparse concat.
sp_expand_dim = tf.sparse.expand_dims(sp, axis=1)
sp_tiled = tf.sparse.concat(sp_inputs=[sp_expand_dim] * list_size, axis=1)

# Reshape to large abtch before feeding to network. If you networkc an accept 3D tensors, then this step is not needed.
large_batch_sp = tfr.utils.reshape_first_ndims(sp_tiled, 2, [batch_size * list_size])
print(tf.sparse.to_dense(large_batch_sp))
```

Can you check if this works for you?

**Comment by martinbomio** [comment] 2021-01-29 00:25
I tried the above in:

```python
    def build_ELWC_parsing_serving_input_receiver_fn(self,
                                                     default_batch_size=None,
                                                     input_name="inputs"):
        context_feature_spec, example_feature_spec = self.create_feature_spec_for_elwc()

        def serving_input_receiver_fn():
            """An input_fn that expects a serialized ExampleListWithContext."""
            serialized = tf.compat.v1.placeholder(
                dtype=tf.dtypes.string,
                shape=[default_batch_size],
                name="input_ranking_tensor",
            )
            receiver_tensors = {input_name: serialized}
            features = tfr.data.parse_from_example_list(
                serialized,
                context_feature_spec=context_feature_spec,
                example_feature_spec=example_feature_spec,
                size_feature_name="list_size"
            )

            list_size = features["list_size"]
            print(f"List Size: {list_size}")
            print(f"List Size Shape: {tf.shape(list_size)}")
            if context_feature_spec:
                for name in context_feature_spec.keys():
                    shape = tf.shape(features[name])
                    if isinstance(features[name], tf.SparseTensor):
                        sp_expand_dim = tf.sparse.expand_dims(features[name], axis=1)
                        features[name] = tf.sparse.concat(sp_inputs=[sp_expand_dim] * list_size, axis=1)
                    else:
                        context_feature = tf.expand_dims(features[name], axis=1)
                        features[name] = tf.tile(context_feature, multiples=[shape[0], list_size, shape[1]])


            # Since the models accept 2D tensors of we need to reshape all of the feature
            # tensors to have dimensions (batch_size * list_size, feature_dim)
            for name in features.keys():
                if name != "list_size":
                    shape = tf.shape(features[name])
                    new_shape = [shape[0] * shape[1], shape[2]]
                    if isinstance(features[name], tf.SparseTensor):
                        features[name] = tf.sparse.reshape(features[name], new_shape)
                    else:
                        features[name] = tf.reshape(features[name], shape=new_shape)
                return ServingInputReceiver(features, receiver_tensors)

        return serving_input_receiver_fn
```

note the part where I am manipulating the context features differently between sparse tensors and dense ones.
I am getting the following error:
```
TypeError: Expected int32, got <tensorflow.python.framework.sparse_tensor.SparseTensor object at 0x19d6c53c8> of type 'SparseTensor' instead.
```

on this line: `features[name] = tf.sparse.concat(sp_inputs=[sp_expand_dim] * list_size, axis=1)`

**Comment by martinbomio** [comment] 2021-01-29 00:40
an option here maybe is to tile de serialized example tensor for the context features since that would always be a dense tensor?

**Comment by ramakumar1729** [comment] 2021-01-29 00:47
Right, I think the term `list_size` is overloaded here. I'd recommend using a different name for `size_feature_name`, e.g., `sizes`.

This is slightly hacky and uses an example feature to infer the "list_size"
Can you try the following:
```
list_size_ = example_feature.get_shape().as_list()[1]  # Works if example_feature is dense or sparse.

# Do tiling via sparse expand_dim and sparse concat.
sp_expand_dim = tf.sparse.expand_dims(sp, axis=1)
sp_tiled = tf.sparse.concat(sp_inputs=[sp_expand_dim] * list_size_, axis=1)
large_batch_sp = tfr.utils.reshape_first_ndims(sp_tiled, 2, [batch_size *list_size_])
print(tf.sparse.to_dense(large_batch_sp))
```

You could also infer the "list_size" from `features[size_feature_name] ` as `tf.reduce_max(features[size_feature_name])`.

**Comment by martinbomio** [comment] 2021-01-29 02:03
@ramakumar1729 thaks for the suggestion. 

I tried both ways and I am still getting the following error:
```
TypeError: Expected int32, got <tensorflow.python.framework.sparse_tensor.SparseTensor object at 0x1a7dfacf8> of type 'SparseTensor' instead.
```

**Comment by martinbomio** [comment] 2021-01-29 18:05
@ramakumar1729 I think the issue is in this line:
```
sp_tiled = tf.sparse.concat(sp_inputs=[sp_expand_dim] * list_size_, axis=1)

```

specifically here: [sp_expand_dim] * list_size_, it seems like multiplying tensors like that doesn't yield what we expect, since both `sp_expand_dim` and `list_size_` are tensors

**Comment by ramakumar1729** [comment] 2021-01-29 18:53
@martinbomio : Can you print the shape of `list_size` tensor and check if it is a scalar? if you can provide a minimum reproducible code to test this, that would be great. 

I'd also recommend using `make_dnn_ranking_estimator` instead which should directly work with standard serving_input_fn builders from tf-ranking.

**Comment by martinbomio** [comment] 2021-01-29 21:58
@ramakumar1729 if `get_shape().to_list()` is used and then the result is indeed not a tensor, but it will contain dimensions as `None` in particular those dimensions that represent variable sizes, such as the `bactch_size` and `list_size`.

I am working on a minimal code to test this. We ended up doing something rather hacky to deal with sparse features, we convert them to dense, reshape them and tile them, and then convert them back to sparse tensors. This is not ideal though.
Right now we are running into some issues with mismatch of dimension sizes when creating the input layer

**Comment by martinbomio** [comment] 2021-02-03 00:50
hi @ramakumar1729, I saw that you guys released a new version with https://github.com/tensorflow/ranking/blob/a197718f2d8eb71e02b5d164bcf72d08716cb6b2/tensorflow_ranking/python/keras/layers.py#L28, which is exactly what we need and have implemented! Are there any plans to expose these operations not as keras layers?

**Comment by ramakumar1729** [comment] 2021-02-03 23:06
@martinbomio : Thanks for taking a look at the new features so quickly. `FlattenList` layer should work along with TF1 code. If you face any issues with SavedModel creation, let us know.

**Comment by ramakumar1729** [comment] 2021-02-24 15:42
@martinbomio : Is this still an issue?

**Comment by ramakumar1729** [comment] 2021-02-25 19:54
Closing this for now. Since the issue of parsing ELWC for a ranking `serving_input_fn` has been addressed in some of the comments, I'll close this. For a custom `serving_input_fn` related issues, feel free to reopen or I'd recommend starting a new issue.

**Closed by ramakumar1729** 2021-02-25 19:54 UTC
