### ISSUE TITLE
Using TFR MRR Metric in Keras Model

### ISSUE THREAD

**Issue by eggie5** [tensorflow/ranking#266] opened 2021-06-09 00:20 UTC
I'm trying to use the TFR MRR metric as a Keras metric. 

My Keras model has a softmax output layer. I've defined this metric according the Keras interface:

```
def mrr_metric_fn(y_true, y_pred):
   """compute MRR with binary relevance label"""
    mrr_fn = metrics.make_ranking_metric_fn(metrics.RankingMetricKey.MRR, topn=20)

    y_true_revel = tf.reshape(y_true, [-1]) #[None, 1]
    y_true_one_hot = tf.one_hot(y_true_revel,  OUTPUT_DIM) #[None, OUTPUT_DIM]
    
    _, mrr = mrr_fn(y_true_one_hot, y_pred, {})
    return mrr
```

TF 2.3, I get this error:

```
model.compile(loss='sparse_categorical_crossentropy', optimizer=opt, metrics=["accuracy", mrr_metric_fn], )
history = model.fit(train_dataset, epochs=EPOCHS, validation_data=val_dataset, callbacks=callbacks)
```

```
    /home/aegg/.local/lib/python3.7/site-packages/tensorflow_ranking/python/metrics.py:269 compute  *
        return tf.compat.v1.metrics.mean(mrr, per_list_weights)
    /home/aegg/.local/lib/python3.7/site-packages/tensorflow/python/ops/metrics_impl.py:365 mean  **
        total = metric_variable([], dtypes.float32, name='total')
    /home/aegg/.local/lib/python3.7/site-packages/tensorflow/python/ops/metrics_impl.py:85 metric_variable
        name=name)
    /home/aegg/.local/lib/python3.7/site-packages/tensorflow/python/ops/variables.py:260 __call__
        return cls._variable_v1_call(*args, **kwargs)
    /home/aegg/.local/lib/python3.7/site-packages/tensorflow/python/ops/variables.py:221 _variable_v1_call
        shape=shape)
    /home/aegg/.local/lib/python3.7/site-packages/tensorflow/python/ops/variables.py:67 getter
        return captured_getter(captured_previous, **kwargs)
    /home/aegg/.local/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py:2857 creator
        return next_creator(**kwargs)
    /home/aegg/.local/lib/python3.7/site-packages/tensorflow/python/ops/variables.py:67 getter
        return captured_getter(captured_previous, **kwargs)
    /home/aegg/.local/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py:2857 creator
        return next_creator(**kwargs)
    /home/aegg/.local/lib/python3.7/site-packages/tensorflow/python/ops/variables.py:67 getter
        return captured_getter(captured_previous, **kwargs)
    /home/aegg/.local/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py:2857 creator
        return next_creator(**kwargs)
    /home/aegg/.local/lib/python3.7/site-packages/tensorflow/python/ops/variables.py:67 getter
        return captured_getter(captured_previous, **kwargs)
    /home/aegg/.local/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py:702 invalid_creator_scope
        "tf.function-decorated function tried to create "

    ValueError: tf.function-decorated function tried to create variables on non-first call.

```

Any idea what this error means??

**Comment by rjagerman** [comment] 2021-06-09 12:05
I am not sure about this error specifically, but I suspect the problem is that:

```
mrr_fn = metrics.make_ranking_metric_fn(metrics.RankingMetricKey.MRR, topn=20)
```

is creating a new metric function on every call to `mrr_metric_fn()`. Perhaps you can define the `mrr_fn` outside of the `mrr_metric_fn()`, i.e. something like:

```python
mrr_fn = metrics.make_ranking_metric_fn(metrics.RankingMetricKey.MRR, topn=20)

def mrr_metric_fn(y_true, y_pred):
   """compute MRR with binary relevance label"""
    y_true_revel = tf.reshape(y_true, [-1]) #[None, 1]
    y_true_one_hot = tf.one_hot(y_true_revel,  OUTPUT_DIM) #[None, OUTPUT_DIM]
    
    _, mrr = mrr_fn(y_true_one_hot, y_pred, {})
    return mrr
```

Alternatively you can try using the provided Keras ranking metrics/losses in `tensorflow_ranking.keras.*`:

```python
import tensorflow as tf
import tensorflow_ranking as tfr

mrr_metric_fn = tfr.keras.metrics.MRRMetric(topn=20)
mrr_metric_fn(
    y_true=tf.constant([[0, 0, 1]]),
    y_pred=tf.constant([[0., 2., 1.]]))
# Produces:
# <tf.Tensor: shape=(), dtype=float32, numpy=0.5>
```

If it fits your use-case, you should be able to use the `tensorflow_ranking.keras.*` losses and metrics directly in `model.compile()`, e.g.:

```python
approx_ndcg_loss = tfr.keras.losses.ApproxNDCGLoss()
mrr_metric = tfr.keras.metrics.MRRMetric(topn=20)

# ...
model.compile(loss=approx_ndcg_loss, metrics=[mrr_metric])
```

**Comment by eggie5** [comment] 2021-06-09 13:45
@rjagerman surprised to see your answer here! Have followed the work of you and Harrie on Counterfactual LTR work at UvA. 

I originally did call the factory `metrics.make_ranking_metric_fn` outside of the metric function, like you suggested but that had the same error.

I was surprised to see that TRF has a `Keras` module!I was on a rather old version of TRF so I upgraded to `0.3.1` and was able to get this to work:

```
mrr_metric = tfr.keras.metrics.MRRMetric(topn=20)
def mrr_metric_fn(y_true, y_pred):

    y_true_revel = tf.reshape(y_true, [-1])
    y_true_sparse = tf.one_hot(tf.cast(y_true_revel, tf.int32), OUTPUT_DIM)
    
    mrr = mrr_metric(y_true_sparse, y_pred)
    return mrr
```

Have to do the reshaping bc my labels/targets are not vectors.

Thanks.

**Comment by rjagerman** [comment] 2021-06-10 11:23
Hi @eggie5, I have recently joined Google after finishing my PhD at UvA, hence me working on TF-Ranking now. :-) 

Glad to hear that using the Keras version of the MRR metric works! I'll go ahead and close this issue as it is solved.

**Closed by rjagerman** 2021-06-10 11:23 UTC
