### ISSUE TITLE
NanLossDuringTrainingError: NaN loss during training.

### ISSUE THREAD

**Issue by amir-rahnama** [tensorflow/ranking#232] opened 2020-09-21 10:06 UTC
I am using the example you guys provided under 'https://github.com/tensorflow/ranking/blob/master/tensorflow_ranking/examples/tf_ranking_libsvm.py' and I am using it for LETOR 4's MQ2008-list example. So the only difference here is that the label is relevance So basically I am interested to train the model on a list-wise loss. 

The only changes I am making to the example is the following:
* Changing the group_size to something above 1. I assume this will enable features to be transformed into the list-wise approach
* Changing the loss to approx_ndcg_loss

I am not exactly sure why but I am getting NanLossDuringTrainingError: NaN loss during training. So I wonder if I am missing something here. Now if I change the loss back to pairwise_logistic_loss, everything works just fine. 

What would be the right approach to model the MQ2008-list dataset in that example?

**Comment by ramakumar1729** [comment] 2020-11-10 03:36
@amir-rahnama Can you try with a lower learning rate? Sometimes a larger learning rate can cause NaN loss.

**Comment by ramakumar1729** [comment] 2021-02-02 17:02
@amir-rahnama : Are you still facing this issue? Did a lower learning rate help?

**Comment by ramakumar1729** [comment] 2021-02-03 23:07
Closing this issue for now. Please feel free to reopen.

**Closed by ramakumar1729** 2021-02-03 23:07 UTC

**Comment by samanemami** [comment] 2021-08-22 09:59
Hi @ramakumar1729 
I have the same problem with [BoostedTree](https://www.tensorflow.org/tutorials/estimator/boosted_trees_model_understanding).
I tried the lower learning rate, but the problem is still there.

I am tunning the hyper-params including, learning rate and tree depth.
